# VendiMap Android Release Keystore Properties
# Fill in these values for Google Play Store release build signature.
# storeFile path is relative to the root project directory.

storeFile=release.keystore
storePassword=vendimaprelease
keyAlias=vendix-key
keyPassword=vendimaprelease
