export const initialSpots = [
    {
        id: 1,
        name: "サントリー 渋谷センター街店",
        lat: 35.6605,
        lng: 139.7005,
        manufacturer: "サントリー",
        rating: 4.5,
        priceRange: "130円〜180円",
        hasTrashBin: "あり (回収頻度高)",
        paymentMethods: ["現金", "交通系IC", "PayPay"],
        rarity: 2,
        lineup: ["天然水", "BOSS", "ZONe"],
        description: "渋谷のど真ん中にある、いつもキンキンに冷えた自販機。ゴミ箱も併設されていて綺麗。",
        type: "standard",
        photos: ["https://images.unsplash.com/photo-1582239454157-19d675eb825f?auto=format&fit=crop&q=80&w=400"],
        verifiedCount: 15,
        lastUpdated: "2026/05/18"
    },
    {
        id: 2,
        name: "ダイドードリンコ 激レア自販機",
        lat: 35.6625,
        lng: 139.6985,
        manufacturer: "ダイドー",
        rating: 4.8,
        priceRange: "100円〜160円",
        hasTrashBin: "なし",
        paymentMethods: ["現金"],
        rarity: 5,
        lineup: ["復刻堂", "飲む缶カレー", "おしるこ"],
        description: "なかなか見かけない復刻シリーズや、変わり種飲料が豊富。自販機マニア必見！",
        type: "rare",
        photos: ["https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&q=80&w=400"],
        verifiedCount: 8,
        lastUpdated: "2026/05/17"
    },
    {
        id: 3,
        name: "格安 100円自販機 (コインパーキング横)",
        lat: 35.6585,
        lng: 139.7025,
        manufacturer: "その他",
        rating: 3.9,
        priceRange: "80円〜110円",
        hasTrashBin: "あり (ペットボトルのみ)",
        paymentMethods: ["現金のみ"],
        rarity: 1,
        lineup: ["お茶", "炭酸水", "コーヒー"],
        description: "とにかく安い。ドライバーの休憩スポットとして重宝されている。",
        type: "cheap",
        photos: [],
        verifiedCount: 2,
        lastUpdated: "2026/04/20"
    },
    {
        id: 4,
        name: "秋葉原おでん缶自販機 (万世橋近く)",
        lat: 35.6997,
        lng: 139.7715,
        manufacturer: "その他",
        rating: 4.9,
        priceRange: "300円〜350円",
        hasTrashBin: "あり (缶専用特大)",
        paymentMethods: ["現金", "Suica", "iD"],
        rarity: 5,
        lineup: ["おでん缶(つみれ入)", "おでん缶(大根)", "ラーメン缶"],
        description: "アキバ名物おでん缶の元祖自販機。秋葉原電気街を散策する観光客に絶大な人気を誇る伝説のスポット。",
        type: "rare",
        photos: [],
        verifiedCount: 124,
        lastUpdated: "2026/05/18"
    },
    {
        id: 5,
        name: "歌舞伎町ネオン街自販機",
        lat: 35.6938,
        lng: 139.7034,
        manufacturer: "コカ・コーラ",
        rating: 4.2,
        priceRange: "140円〜210円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "交通系IC", "PayPay", "LINE Pay"],
        rarity: 2,
        lineup: ["コカ・コーラ", "リアルゴールド", "ジョージア"],
        description: "不夜城新宿歌舞伎町で眠らない人々を支えるエナジーチャージ特化型自販機。",
        type: "standard",
        photos: [],
        verifiedCount: 42,
        lastUpdated: "2026/05/10"
    },
    {
        id: 6,
        name: "銀座プレミアムゴールド自販機",
        lat: 35.6712,
        lng: 139.7667,
        manufacturer: "サントリー",
        rating: 4.7,
        priceRange: "180円〜300円",
        hasTrashBin: "あり (スタイリッシュステンレス)",
        paymentMethods: ["交通系IC", "クレジットカード", "PayPay"],
        rarity: 4,
        lineup: ["プレミアムボス", "特茶", "山崎の炭酸水"],
        description: "高級ブティックが並ぶ銀座に馴染むよう特別にゴールドメッキ加工された超プレミアム自販機。",
        type: "rare",
        photos: [],
        verifiedCount: 18,
        lastUpdated: "2026/05/15"
    },
    {
        id: 7,
        name: "浅草木目調伝統自販機 (雷門裏手)",
        lat: 35.7147,
        lng: 139.7967,
        manufacturer: "アサヒ",
        rating: 4.6,
        priceRange: "130円〜180円",
        hasTrashBin: "あり (和風木目デザイン)",
        paymentMethods: ["現金", "交通系IC", "WeChat Pay", "Alipay"],
        rarity: 3,
        lineup: ["十六茶", "ワンダ", "三ツ矢サイダー"],
        description: "歴史的街並みを損なわない木目ラッピング仕様。海外観光客の決済方法が非常に豊富。",
        type: "standard",
        photos: [],
        verifiedCount: 65,
        lastUpdated: "2026/05/16"
    },
    {
        id: 8,
        name: "道頓堀お好み焼きソース缶自販機",
        lat: 34.6687,
        lng: 135.5013,
        manufacturer: "その他",
        rating: 4.8,
        priceRange: "300円〜500円",
        hasTrashBin: "なし",
        paymentMethods: ["現金", "PayPay"],
        rarity: 5,
        lineup: ["たこ焼きソース", "お好み焼きソース", "ヘルメスソース"],
        description: "大阪・ミナミの観光客向けウケ狙いお土産ソース自販機。SNSで大バズり中！",
        type: "rare",
        photos: [],
        verifiedCount: 88,
        lastUpdated: "2026/05/18"
    },
    {
        id: 9,
        name: "日本橋激安50円自販機 (オタロード横)",
        lat: 34.6588,
        lng: 135.5057,
        manufacturer: "その他",
        rating: 4.4,
        priceRange: "50円〜100円",
        hasTrashBin: "あり (満杯になりがち)",
        paymentMethods: ["現金のみ"],
        rarity: 1,
        lineup: ["激安コーラ", "缶コーヒー", "謎の炭酸水"],
        description: "驚異の全品50円〜！何が出てくるかわからない『お楽しみ缶』が100円で売られている大阪名物激安スポット。",
        type: "cheap",
        photos: [],
        verifiedCount: 97,
        lastUpdated: "2026/05/19"
    },
    {
        id: 10,
        name: "京都祇園伝統景観自販機",
        lat: 35.0037,
        lng: 135.7782,
        manufacturer: "コカ・コーラ",
        rating: 4.7,
        priceRange: "150円〜200円",
        hasTrashBin: "あり (格子枠付き)",
        paymentMethods: ["現金", "交通系IC", "Apple Pay"],
        rarity: 4,
        lineup: ["綾鷹", "伊右衛門", "和だし汁"],
        description: "京都市の景観条例を最高ランクで遵守した格子状の木枠に包まれた和テイストの自販機。京都祇園の情緒と完璧に融合。",
        type: "rare",
        photos: [],
        verifiedCount: 33,
        lastUpdated: "2026/05/14"
    },
    {
        id: 11,
        name: "伏見稲荷鳥居カラー自販機",
        lat: 34.9671,
        lng: 135.7727,
        manufacturer: "アサヒ",
        rating: 4.5,
        priceRange: "140円〜190円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "交通系IC", "Alipay"],
        rarity: 3,
        lineup: ["緑茶", "カルピス", "梅よろし"],
        description: "お稲荷さんの総本山にちなんで、鮮やかな「朱色」で全面ラッピングされた千本鳥居モチーフ自販機。",
        type: "standard",
        photos: [],
        verifiedCount: 56,
        lastUpdated: "2026/05/12"
    },
    {
        id: 12,
        name: "名古屋大須かんのん抹茶自販機",
        lat: 35.1599,
        lng: 136.8991,
        manufacturer: "ポッカサッポロ",
        rating: 4.3,
        priceRange: "120円〜180円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "manaca", "PayPay"],
        rarity: 2,
        lineup: ["大須ういろう炭酸", "玉露入りお茶", "ポッカコーヒー"],
        description: "大須観音通り商店街にある、愛知名物のポッカレモンや西尾の抹茶ドリンクを揃えた地域密着自販機。",
        type: "standard",
        photos: [],
        verifiedCount: 14,
        lastUpdated: "2026/05/05"
    },
    {
        id: 13,
        name: "博多中洲天神とんこつスープ缶自販機",
        lat: 33.5902,
        lng: 130.4017,
        manufacturer: "キリン",
        rating: 4.9,
        priceRange: "150円〜250円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "nimoca", "LINE Pay"],
        rarity: 5,
        lineup: ["飲む博多とんこつスープ", "焼きあご出汁", "生茶"],
        description: "とんこつラーメンスープをそのまま温かい缶にしたラーメン県ならではの激レア特化型自販機。〆の一杯に最適。",
        type: "rare",
        photos: [],
        verifiedCount: 110,
        lastUpdated: "2026/05/18"
    },
    {
        id: 14,
        name: "札幌すすきの極寒ガラナ自販機",
        lat: 43.0556,
        lng: 141.3537,
        manufacturer: "キリン",
        rating: 4.6,
        priceRange: "130円〜180円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "Kitaca", "PayPay"],
        rarity: 3,
        lineup: ["コアップガラナ", "リボンナポリン", "冷やしコーンスープ"],
        description: "北海道民のソウルドリンク「ガラナ」と「ナポリン」が前面に推された、北の大地の熱気を感じる自販機。",
        type: "standard",
        photos: [],
        verifiedCount: 45,
        lastUpdated: "2026/05/16"
    },
    {
        id: 15,
        name: "小樽運河ガス灯デザイン自販機",
        lat: 43.1912,
        lng: 141.0062,
        manufacturer: "アサヒ",
        rating: 4.8,
        priceRange: "150円〜220円",
        hasTrashBin: "あり (レトロな鋳鉄調)",
        paymentMethods: ["交通系IC", "iD", "QUICPay"],
        rarity: 4,
        lineup: ["小樽サイダー風味", "十勝ミルクココア", "おいしい水"],
        description: "小樽運河のシンボル「ガス灯」のレトロな美観を再現したブロンズ仕上げのロマンチック自販機。",
        type: "rare",
        photos: [],
        verifiedCount: 29,
        lastUpdated: "2026/05/11"
    },
    {
        id: 16,
        name: "仙台国分町牛タンだしスープ自販機",
        lat: 38.2638,
        lng: 140.8698,
        manufacturer: "ダイドー",
        rating: 4.4,
        priceRange: "140円〜200円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "icsca", "PayPay"],
        rarity: 4,
        lineup: ["テールスープ風スープ缶", "冷製ずんだシェイク缶", "デミグラススープ"],
        description: "東北一の歓楽街国分町のビル陰にひっそり佇む、牛タンテールスープ風味やずんだシェイク缶を売る変わり種スポット。",
        type: "rare",
        photos: [],
        verifiedCount: 16,
        lastUpdated: "2026/04/28"
    },
    {
        id: 17,
        name: "横浜中華街杏仁豆腐ジュース自販機",
        lat: 35.4422,
        lng: 139.6472,
        manufacturer: "その他",
        rating: 4.7,
        priceRange: "160円〜260円",
        hasTrashBin: "あり (パンダデザイン)",
        paymentMethods: ["現金", "PayPay", "微信支付"],
        rarity: 5,
        lineup: ["飲む杏仁豆腐", "マンゴープリンジュース", "プーアル茶"],
        description: "中華街の中に設置されたデザート缶特化型自販機。飲む杏仁豆腐は濃厚で非常に美味しくリピーター続出。",
        type: "rare",
        photos: [],
        verifiedCount: 52,
        lastUpdated: "2026/05/18"
    },
    {
        id: 18,
        name: "沖縄国際通りさんぴん茶パラダイス",
        lat: 26.2144,
        lng: 127.6853,
        manufacturer: "ダイドー",
        rating: 4.9,
        priceRange: "100円〜150円",
        hasTrashBin: "あり (シーサーデコレーション)",
        paymentMethods: ["現金", "OKICA", "PayPay", "au PAY"],
        rarity: 3,
        lineup: ["さんぴん茶", "シークヮーサーソーダ", "バヤリースオレンジ"],
        description: "沖縄の国際通りの真ん中に位置し、何種類ものメーカーの「さんぴん茶」だけをずらりと集めたさんぴん茶マニア歓喜の自販機。",
        type: "standard",
        photos: [],
        verifiedCount: 93,
        lastUpdated: "2026/05/19"
    },
    {
        id: 19,
        name: "広島平和記念公園レモンソーダ自販機",
        lat: 34.3955,
        lng: 132.4536,
        manufacturer: "コカ・コーラ",
        rating: 4.3,
        priceRange: "130円〜180円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "PASPY", "PayPay"],
        rarity: 2,
        lineup: ["瀬戸内レモンソーダ", "コカ・コーラ", "いろはす"],
        description: "広島平和記念公園近くの、瀬戸内産レモン果汁を使用したさわやかなレモンソーダが大人気の自販機。",
        type: "standard",
        photos: [],
        verifiedCount: 22,
        lastUpdated: "2026/05/01"
    },
    {
        id: 20,
        name: "金沢兼六園金箔アートお茶自販機",
        lat: 36.5621,
        lng: 136.6622,
        manufacturer: "アサヒ",
        rating: 4.8,
        priceRange: "200円〜400円",
        hasTrashBin: "あり (漆調)",
        paymentMethods: ["交通系IC", "クレジットカード", "PayPay"],
        rarity: 5,
        lineup: ["金箔加賀棒茶", "プレミアム十六茶", "抹茶ラテ"],
        description: "兼六園前の、金沢を代表する伝統工芸「金箔」をちりばめた豪華絢爛な漆塗り風デザイン自販機。",
        type: "rare",
        photos: [],
        verifiedCount: 31,
        lastUpdated: "2026/05/15"
    },
    {
        id: 21,
        name: "東京タワー展望レッドネオン自販機",
        lat: 35.6586,
        lng: 139.7454,
        manufacturer: "コカ・コーラ",
        rating: 4.6,
        priceRange: "160円〜250円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "交通系IC", "クレジットカード"],
        rarity: 3,
        lineup: ["コカ・コーラ スリムボトルタワーデザイン", "リアルゴールド", "天然水"],
        description: "東京タワーのふもとで夜間になるとタワーと同じ真っ赤なネオンでライトアップされる映えスポット自販機。",
        type: "standard",
        photos: [],
        verifiedCount: 47,
        lastUpdated: "2026/05/17"
    },
    {
        id: 22,
        name: "那覇空港パイナップルシャワー自販機",
        lat: 26.2064,
        lng: 127.6465,
        manufacturer: "その他",
        rating: 4.5,
        priceRange: "120円〜180円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "OKICA", "PayPay", "交通系IC"],
        rarity: 3,
        lineup: ["パイナップルシャワー", "沖縄シークヮーサー", "ルートビア缶"],
        description: "那覇空港到着ロビー横にある、沖縄限定のトロピカル炭酸ジュースやA&Wルートビアがキンキンに冷えた南国ウェルカム自販機。",
        type: "standard",
        photos: [],
        verifiedCount: 74,
        lastUpdated: "2026/05/18"
    },
    {
        id: 23,
        name: "梅田スカイビルデジタルスクリーン自販機",
        lat: 34.7024,
        lng: 135.4959,
        manufacturer: "サントリー",
        rating: 4.5,
        priceRange: "150円〜220円",
        hasTrashBin: "あり (スマート投入口)",
        paymentMethods: ["交通系IC", "PayPay", "クレジットカード"],
        rarity: 4,
        lineup: ["プレミアムボス", "ペプシBIG", "緑茶"],
        description: "近づくと透過型液晶デジタルディスプレイに2026年のバズ・インテントトレンド情報や天気予報がシームレスに表示される最新鋭自販機。",
        type: "rare",
        photos: [],
        verifiedCount: 18,
        lastUpdated: "2026/05/15"
    },
    {
        id: 24,
        name: "みなとみらいコスモビュー激安自販機",
        lat: 35.4578,
        lng: 139.6322,
        manufacturer: "その他",
        rating: 4.2,
        priceRange: "90円〜130円",
        hasTrashBin: "あり",
        paymentMethods: ["現金のみ"],
        rarity: 1,
        lineup: ["格安レモン水", "ブレンドコーヒー", "炭酸サイダー"],
        description: "みなとみらいの豪華な夜景を一望できる隠れカップルスポット近くにある、周辺相場から明らかに安い格安自販機。",
        type: "cheap",
        photos: [],
        verifiedCount: 11,
        lastUpdated: "2026/05/09"
    },
    {
        id: 25,
        name: "おたる運河極冷ミルク缶自販機",
        lat: 43.1913,
        lng: 141.0064,
        manufacturer: "アサヒ",
        rating: 4.9,
        priceRange: "200円〜350円",
        hasTrashBin: "あり",
        paymentMethods: ["現金", "Kitaca", "クレジットカード"],
        rarity: 5,
        lineup: ["飲むプレミアム生ミルク缶", "極みミルクココア", "十勝バターコーンスープ"],
        description: "小樽運河のたもとに佇む、北海道十勝産牛乳を使用した濃厚冷え冷え生ミルクココアが味わえる極上スポット。",
        type: "rare",
        photos: [],
        verifiedCount: 68,
        lastUpdated: "2026/05/18"
    }
];
